- ros_topic_name: /camera
  ros_type_name: sensor_msgs/msg/Image
  gz_topic_name: /camera
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS

- ros_topic_name: /cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  gz_topic_name: /cmd_vel
  gz_type_name: gz.msgs.Twist
  direction: ROS_TO_GZ

- ros_topic_name: /person_cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  gz_topic_name: /person_cmd_vel
  gz_type_name: gz.msgs.Twist
  direction: ROS_TO_GZ
